/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Tutorial {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'content' : string,
  'difficulty' : string,
  'slug' : string,
  'tags' : Array<string>,
  'description' : string,
  'codeExample' : string,
  'category' : string,
  'estimatedMinutes' : bigint,
}
export interface TutorialSummary {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'difficulty' : string,
  'slug' : string,
  'description' : string,
  'category' : string,
  'estimatedMinutes' : bigint,
}
export interface UserProfile { 'name' : string }
export interface UserProgress { 'completedAt' : Time, 'tutorialId' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<[string, bigint]>>,
  'getFeaturedTutorials' : ActorMethod<[], Array<TutorialSummary>>,
  'getStats' : ActorMethod<
    [],
    {
      'totalCompletions' : bigint,
      'totalUsers' : bigint,
      'totalTutorials' : bigint,
    }
  >,
  'getTutorial' : ActorMethod<[string], Tutorial>,
  'getTutorials' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    Array<TutorialSummary>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], Array<UserProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markComplete' : ActorMethod<[bigint], undefined>,
  'markIncomplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];