/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TutorialSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'difficulty' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'estimatedMinutes' : IDL.Nat,
});
export const Tutorial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'content' : IDL.Text,
  'difficulty' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'codeExample' : IDL.Text,
  'category' : IDL.Text,
  'estimatedMinutes' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserProgress = IDL.Record({
  'completedAt' : Time,
  'tutorialId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getFeaturedTutorials' : IDL.Func([], [IDL.Vec(TutorialSummary)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCompletions' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalTutorials' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTutorial' : IDL.Func([IDL.Text], [Tutorial], ['query']),
  'getTutorials' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(TutorialSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markComplete' : IDL.Func([IDL.Nat], [], []),
  'markIncomplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TutorialSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'difficulty' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'estimatedMinutes' : IDL.Nat,
  });
  const Tutorial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'content' : IDL.Text,
    'difficulty' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'codeExample' : IDL.Text,
    'category' : IDL.Text,
    'estimatedMinutes' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserProgress = IDL.Record({
    'completedAt' : Time,
    'tutorialId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getFeaturedTutorials' : IDL.Func(
        [],
        [IDL.Vec(TutorialSummary)],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCompletions' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalTutorials' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTutorial' : IDL.Func([IDL.Text], [Tutorial], ['query']),
    'getTutorials' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(TutorialSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markComplete' : IDL.Func([IDL.Nat], [], []),
    'markIncomplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };